export const testCases = [
    {
      name: "TC1 – StraightThrough - TEST",
      make: "Ford",
      enginePerformance: 500,
      dateOfManufactor: "dateMinus3years",
      numerOfSeats: 5,
      fuelType: "Petrol",
      listPrice: 20000,
      annualMileage: 50000,
      firstName: "Christoph",
      lastname: "Hiess",
      age: 26,
      gender: "Male",
      country: "United States",
      zipCode: 1234,
      occupation: "Employee",
      hobbies: "Speeding",
      startDate: "startDatePlus1M1D",
      insuranceSum: "7.000.000,00",
      meritRating: "Bonus 5",
      damageInsurance: "Partial Coverage",
      optionalEuroProtection: false,
      optionalLegalDefenseInsurance: true,
      courtesyCar: "No",
      priceSilver: "331.00",
      priceGold: "977.00",
      pricePlatinum: "1,917.00",
      priceUltimate: "3,652.00",
      email: "2410781009@fhb.at",
      username: "testCase01",
      password: "Password01",
      passwordConfirm: "Password01"
    },
    {
      name: "TC2 – Engine performance between 1000 and 2000",
      make: "Ford",
      enginePerformance: 1500,
      dateOfManufactor: "dateMinus3years",
      numerOfSeats: 5,
      fuelType: "Petrol",
      listPrice: 20000,
      annualMileage: 50000,
      firstName: "Maximilian",
      lastname: "Resch",
      age: 26,
      gender: "Male",
      country: "United States",
      zipCode: 4321,
      occupation: "Employee",
      hobbies: "Speeding",
      startDate: "startDatePlus1M1D",
      insuranceSum: "7.000.000,00",
      meritRating: "Bonus 5",
      damageInsurance: "Partial Coverage",
      optionalEuroProtection: false,
      optionalLegalDefenseInsurance: true,
      courtesyCar: "No",
      priceSilver: "337.00",
      priceGold: "993.00",
      pricePlatinum: "1,949.00",
      priceUltimate: "3,712.00",
      email: "2410781005@fhb.at",
      username: "testCase02",
      password: "Password01",
      passwordConfirm: "Password01"
    },
    {
      name: "TC3 – Manufactured more than 5 Years in the Past",
      make: "Ford",
      enginePerformance: 500,
      dateOfManufactor: "dateMinus10years",
      numerOfSeats: 5,
      fuelType: "Petrol",
      listPrice: 20000,
      annualMileage: 50000,
      firstName: "Franz",
      lastname: "Hermann",
      age: 26,
      gender: "Male",
      country: "United States",
      zipCode: 4321,
      occupation: "Employee",
      hobbies: "Speeding",
      startDate: "startDatePlus1M1D",
      insuranceSum: "7.000.000,00",
      meritRating: "Bonus 5",
      damageInsurance: "Partial Coverage",
      optionalEuroProtection: false,
      optionalLegalDefenseInsurance: true,
      courtesyCar: "No",
      priceSilver: "334.00",
      priceGold: "983.00",
      pricePlatinum: "1,931.00",
      priceUltimate: "3,678.00",
      email: "2410781005@fhb.at",
      username: "testCase03",
      password: "Password01",
      passwordConfirm: "Password01"
    },
    {
      name: "TC4 – List price between 50K and 100K",
      make: "Ford",
      enginePerformance: 500,
      dateOfManufactor: "dateMinus3years",
      numerOfSeats: 5,
      fuelType: "Petrol",
      listPrice: 75000,
      annualMileage: 50000,
      firstName: "Erwin",
      lastname: "Staller",
      age: 26,
      gender: "Male",
      country: "United States",
      zipCode: 4321,
      occupation: "Employee",
      hobbies: "Speeding",
      startDate: "startDatePlus1M1D",
      insuranceSum: "7.000.000,00",
      meritRating: "Bonus 5",
      damageInsurance: "Partial Coverage",
      optionalEuroProtection: false,
      optionalLegalDefenseInsurance: true,
      courtesyCar: "No",
      priceSilver: "466.00",
      priceGold: "1,374.00",
      pricePlatinum: "2,697.00",
      priceUltimate: "5,137.00",
      email: "2410781005@fhb.at",
      username: "testCase04",
      password: "Password01",
      passwordConfirm: "Password01"
    },
    {
      name: "TC5 – Age between 18 and 25 and 56 and 70",
      make: "Ford",
      enginePerformance: 500,
      dateOfManufactor: "dateMinus3years",
      numerOfSeats: 5,
      fuelType: "Petrol",
      listPrice: 20000,
      annualMileage: 50000,
      firstName: "Maximilian",
      lastname: "Resch",
      age: 21,
      gender: "Male",
      country: "United States",
      zipCode: 4321,
      occupation: "Employee",
      hobbies: "Speeding",
      startDate: "startDatePlus1M1D",
      insuranceSum: "7.000.000,00",
      meritRating: "Bonus 5",
      damageInsurance: "Partial Coverage",
      optionalEuroProtection: false,
      optionalLegalDefenseInsurance: true,
      courtesyCar: "No",
      priceSilver: "331.00",
      priceGold: "977.00",
      pricePlatinum: "1,917.00",
      priceUltimate: "3,652.00",
      email: "2410781005@fhb.at",
      username: "testCase05",
      password: "Password01",
      passwordConfirm: "Password01"
    },
    {
      name: "TC6 – Female",
      make: "Ford",
      enginePerformance: 500,
      dateOfManufactor: "dateMinus3years",
      numerOfSeats: 5,
      fuelType: "Petrol",
      listPrice: 20000,
      annualMileage: 50000,
      firstName: "Annette",
      lastname: "Karte",
      age: 26,
      gender: "Female",
      country: "United States",
      zipCode: 4321,
      occupation: "Employee",
      hobbies: "Speeding",
      startDate: "startDatePlus1M1D",
      insuranceSum: "7.000.000,00",
      meritRating: "Bonus 5",
      damageInsurance: "Partial Coverage",
      optionalEuroProtection: false,
      optionalLegalDefenseInsurance: true,
      courtesyCar: "No",
      priceSilver: "331.00",
      priceGold: "947.00",
      pricePlatinum: "1,917.00",
      priceUltimate: "3,652.00",
      email: "2410781005@fhb.at",
      username: "testCase06",
      password: "Password01",
      passwordConfirm: "Password01"
    }
  ];
