export const testCases = [
    {
      name: "TC1 – Standardkunde",
      make: "Ford",
      enginePerformance: 1500,
      dateOfManufactor: "dateMinus3years",
      numerOfSeats: 5,
      fuelType: "Petrol",
      listPrice: 75000,
      annualMileage: 50000,
      firstName: "Christoph",
      lastname: "Hiess",
      age: 25,
      gender: "Female",
      country: "United States",
      zipCode: 1234,
      occupation: "Employee",
      hobbies: "Speeding",
      startDate: "startDatePlus1M1D",
      insuranceSum: "7.000.000,00",
      meritRating: "Bonus 5",
      damageInsurance: "Partial Coverage",
      optionalEuroProtection: true,
      optionalLegalDefenseInsurance: true,
      courtesyCar: "No",
      priceSilver: "488.00",
      priceGold: "1,439.00",
      pricePlatinum: "2,824.00",
      priceUltimate: "5,380.00",
      email: "2410781009@fhb.at",
      username: "testCase01",
      password: "Password01",
      passwordConfirm: "Password01"
    },
  ];