export const testCases = [
    {
      name: "TC1 – StraightThrough",
      make: "Ford",
      enginePerformance: 500,
      dateOfManufactor: "dateMinus3years",
      numerOfSeats: 5,
      fuelType: "Petrol",
      listPrice: 20000,
      annualMileage: 50000,
      firstName: "Christoph",
      lastname: "Hiess",
      age: 26,
      gender: "Male",
      country: "United States",
      zipCode: 1234,
      occupation: "Employee",
      hobbies: "Speeding",
      startDate: "startDatePlus1M1D",
      insuranceSum: "7.000.000,00",
      meritRating: "Bonus 5",
      damageInsurance: "Partial Coverage",
      optionalEuroProtection: false,
      optionalLegalDefenseInsurance: true,
      courtesyCar: "No",
      priceSilver: "331.00",
      priceGold: "977.00",
      pricePlatinum: "1,917.00",
      priceUltimate: "3,652.00",
      email: "2410781009@fhb.at",
      username: "testCase01",
      password: "Password01",
      passwordConfirm: "Password01"
    },
    {
      name: "TC2 – Engine performance between 1000 and 2000",
      make: "Ford",
      enginePerformance: 1500,
      dateOfManufactor: "dateMinus3years",
      numerOfSeats: 5,
      fuelType: "Petrol",
      listPrice: 20000,
      annualMileage: 50000,
      firstName: "Maximilian",
      lastname: "Resch",
      age: 26,
      gender: "Male",
      country: "United States",
      zipCode: 4321,
      occupation: "Employee",
      hobbies: "Speeding",
      startDate: "startDatePlus1M1D",
      insuranceSum: "7.000.000,00",
      meritRating: "Bonus 5",
      damageInsurance: "Partial Coverage",
      optionalEuroProtection: false,
      optionalLegalDefenseInsurance: true,
      courtesyCar: "No",
      priceSilver: "337.00",
      priceGold: "993.00",
      pricePlatinum: "1,949.00",
      priceUltimate: "3,712.00",
      email: "2410781005@fhb.at",
      username: "testCase02",
      password: "Password01",
      passwordConfirm: "Password01"
    },
    {
      name: "TC3 – Manufactured more than 5 Years in the Past",
      make: "Ford",
      enginePerformance: 500,
      dateOfManufactor: "dateMinus10years",
      numerOfSeats: 5,
      fuelType: "Petrol",
      listPrice: 20000,
      annualMileage: 50000,
      firstName: "Franz",
      lastname: "Hermann",
      age: 26,
      gender: "Male",
      country: "United States",
      zipCode: 4321,
      occupation: "Employee",
      hobbies: "Speeding",
      startDate: "startDatePlus1M1D",
      insuranceSum: "7.000.000,00",
      meritRating: "Bonus 5",
      damageInsurance: "Partial Coverage",
      optionalEuroProtection: false,
      optionalLegalDefenseInsurance: true,
      courtesyCar: "No",
      priceSilver: "334.00",
      priceGold: "983.00",
      pricePlatinum: "1,931.00",
      priceUltimate: "3,678.00",
      email: "2410781005@fhb.at",
      username: "testCase03",
      password: "Password01",
      passwordConfirm: "Password01"
    },
    {
      name: "TC4 – List price between 50K and 100K",
      make: "Ford",
      enginePerformance: 500,
      dateOfManufactor: "dateMinus3years",
      numerOfSeats: 5,
      fuelType: "Petrol",
      listPrice: 75000,
      annualMileage: 50000,
      firstName: "Erwin",
      lastname: "Staller",
      age: 26,
      gender: "Male",
      country: "United States",
      zipCode: 4321,
      occupation: "Employee",
      hobbies: "Speeding",
      startDate: "startDatePlus1M1D",
      insuranceSum: "7.000.000,00",
      meritRating: "Bonus 5",
      damageInsurance: "Partial Coverage",
      optionalEuroProtection: false,
      optionalLegalDefenseInsurance: true,
      courtesyCar: "No",
      priceSilver: "466.00",
      priceGold: "1,374.00",
      pricePlatinum: "2,697.00",
      priceUltimate: "5,137.00",
      email: "2410781005@fhb.at",
      username: "testCase04",
      password: "Password01",
      passwordConfirm: "Password01"
    },
    {
      name: "TC5 – Age between 18 and 25 and 56 and 70",
      make: "Ford",
      enginePerformance: 500,
      dateOfManufactor: "dateMinus3years",
      numerOfSeats: 5,
      fuelType: "Petrol",
      listPrice: 20000,
      annualMileage: 50000,
      firstName: "Maximilian",
      lastname: "Resch",
      age: 21,
      gender: "Male",
      country: "United States",
      zipCode: 4321,
      occupation: "Employee",
      hobbies: "Speeding",
      startDate: "startDatePlus1M1D",
      insuranceSum: "7.000.000,00",
      meritRating: "Bonus 5",
      damageInsurance: "Partial Coverage",
      optionalEuroProtection: false,
      optionalLegalDefenseInsurance: true,
      courtesyCar: "No",
      priceSilver: "331.00",
      priceGold: "977.00",
      pricePlatinum: "1,917.00",
      priceUltimate: "3,652.00",
      email: "2410781005@fhb.at",
      username: "testCase05",
      password: "Password01",
      passwordConfirm: "Password01"
    },
    {
      name: "TC6 – Female",
      make: "Ford",
      enginePerformance: 500,
      dateOfManufactor: "dateMinus3years",
      numerOfSeats: 5,
      fuelType: "Petrol",
      listPrice: 20000,
      annualMileage: 50000,
      firstName: "Annette",
      lastname: "Karte",
      age: 26,
      gender: "Female",
      country: "United States",
      zipCode: 4321,
      occupation: "Employee",
      hobbies: "Speeding",
      startDate: "startDatePlus1M1D",
      insuranceSum: "7.000.000,00",
      meritRating: "Bonus 5",
      damageInsurance: "Partial Coverage",
      optionalEuroProtection: false,
      optionalLegalDefenseInsurance: true,
      courtesyCar: "No",
      priceSilver: "331.00",
      priceGold: "947.00",
      pricePlatinum: "1,917.00",
      priceUltimate: "3,652.00",
      email: "2410781005@fhb.at",
      username: "testCase06",
      password: "Password01",
      passwordConfirm: "Password01"
    },
    {
      name: "TC7 – Start date month after next month",
      make: "Ford",
      enginePerformance: 500,
      dateOfManufactor: "dateMinus3years",
      numerOfSeats: 5,
      fuelType: "Petrol",
      listPrice: 20000,
      annualMileage: 50000,
      firstName: "Franz",
      lastname: "Hubert",
      age: 26,
      gender: "Male",
      country: "United States",
      zipCode: 4321,
      occupation: "Employee",
      hobbies: "Speeding",
      startDate: "startDatePlus2M1D",
      insuranceSum: "7.000.000,00",
      meritRating: "Bonus 5",
      damageInsurance: "Partial Coverage",
      optionalEuroProtection: false,
      optionalLegalDefenseInsurance: true,
      courtesyCar: "No",
      priceSilver: "331.00",
      priceGold: "977.00",
      pricePlatinum: "1,917.00",
      priceUltimate: "3,652.00",
      email: "2410781005@fhb.at",
      username: "testCase07",
      password: "Password01",
      passwordConfirm: "Password01"
    },
    {
      name: "TC8 – Insuarance sum between 15M and 35M",
      make: "Ford",
      enginePerformance: 500,
      dateOfManufactor: "dateMinus3years",
      numerOfSeats: 5,
      fuelType: "Petrol",
      listPrice: 20000,
      annualMileage: 50000,
      firstName: "Holgar",
      lastname: "Ericson",
      age: 26,
      gender: "Male",
      country: "United States",
      zipCode: 4321,
      occupation: "Employee",
      hobbies: "Speeding",
      startDate: "startDatePlus1M1D",
      insuranceSum: "25.000.000,00",
      meritRating: "Bonus 5",
      damageInsurance: "Partial Coverage",
      optionalEuroProtection: false,
      optionalLegalDefenseInsurance: true,
      courtesyCar: "No",
      priceSilver: "338.00",
      priceGold: "995.00",
      pricePlatinum: "1,953.00",
      priceUltimate: "3,721.00",
      email: "2410781005@fhb.at",
      username: "testCase08",
      password: "Password01",
      passwordConfirm: "Password01"
    },
    {
      name: "TC9 – Merit Rating Super Bonus",
      make: "Ford",
      enginePerformance: 500,
      dateOfManufactor: "dateMinus3years",
      numerOfSeats: 5,
      fuelType: "Petrol",
      listPrice: 20000,
      annualMileage: 50000,
      firstName: "Maximilian",
      lastname: "Resch",
      age: 26,
      gender: "Male",
      country: "United States",
      zipCode: 4321,
      occupation: "Employee",
      hobbies: "Speeding",
      startDate: "startDatePlus1M1D",
      insuranceSum: "7.000.000,00",
      meritRating: "Super Bonus",
      damageInsurance: "Partial Coverage",
      optionalEuroProtection: false,
      optionalLegalDefenseInsurance: true,
      courtesyCar: "No",
      priceSilver: "322.00",
      priceGold: "948.00",
      pricePlatinum: "1,861.00",
      priceUltimate: "3,546.00",
      email: "2410781005@fhb.at",
      username: "testCase09",
      password: "Password01",
      passwordConfirm: "Password01"
    },
    {
      name: "TC10 – Merit Rating malus between 10 and 17",
      make: "Ford",
      enginePerformance: 500,
      dateOfManufactor: "dateMinus3years",
      numerOfSeats: 5,
      fuelType: "Petrol",
      listPrice: 20000,
      annualMileage: 50000,
      firstName: "Anthony",
      lastname: "McKinsee",
      age: 26,
      gender: "Male",
      country: "United States",
      zipCode: 4321,
      occupation: "Employee",
      hobbies: "Speeding",
      startDate: "startDatePlus1M1D",
      insuranceSum: "7.000.000,00",
      meritRating: "Malus 13",
      damageInsurance: "Partial Coverage",
      optionalEuroProtection: false,
      optionalLegalDefenseInsurance: true,
      courtesyCar: "No",
      priceSilver: "370.00",
      priceGold: "1,090.00",
      pricePlatinum: "2,141.00",
      priceUltimate: "4,078.00",
      email: "2410781005@fhb.at",
      username: "testCase10",
      password: "Password01",
      passwordConfirm: "Password01"
    },
    {
      name: "TC11 – Damage Insurance No Coverage",
      make: "Ford",
      enginePerformance: 500,
      dateOfManufactor: "dateMinus3years",
      numerOfSeats: 5,
      fuelType: "Petrol",
      listPrice: 20000,
      annualMileage: 50000,
      firstName: "John",
      lastname: "Wild",
      age: 26,
      gender: "Male",
      country: "United States",
      zipCode: 4321,
      occupation: "Employee",
      hobbies: "Speeding",
      startDate: "startDatePlus1M1D",
      insuranceSum: "7.000.000,00",
      meritRating: "Bonus 5",
      damageInsurance: "No Coverage",
      optionalEuroProtection: false,
      optionalLegalDefenseInsurance: true,
      courtesyCar: "No",
      priceSilver: "282.00",
      priceGold: "832.00",
      pricePlatinum: "1,634.00",
      priceUltimate: "3,112.00",
      email: "2410781005@fhb.at",
      username: "testCase11",
      password: "Password01",
      passwordConfirm: "Password01"
    },
    {
      name: "TC12 – Damage Insurance Full Coverage",
      make: "Ford",
      enginePerformance: 500,
      dateOfManufactor: "dateMinus3years",
      numerOfSeats: 5,
      fuelType: "Petrol",
      listPrice: 20000,
      annualMileage: 50000,
      firstName: "Niklas",
      lastname: "Weggeher",
      age: 26,
      gender: "Male",
      country: "United States",
      zipCode: 4321,
      occupation: "Employee",
      hobbies: "Speeding",
      startDate: "startDatePlus1M1D",
      insuranceSum: "7.000.000,00",
      meritRating: "Bonus 5",
      damageInsurance: "Full Coverage",
      optionalEuroProtection: false,
      optionalLegalDefenseInsurance: true,
      courtesyCar: "No",
      priceSilver: "333.00",
      priceGold: "981.00",
      pricePlatinum: "1,927.00",
      priceUltimate: "3,670.00",
      email: "2410781005@fhb.at",
      username: "testCase12",
      password: "Password01",
      passwordConfirm: "Password01"
    },
    {
      name: "TC13 – Euro Protection",
      make: "Ford",
      enginePerformance: 500,
      dateOfManufactor: "dateMinus3years",
      numerOfSeats: 5,
      fuelType: "Petrol",
      listPrice: 20000,
      annualMileage: 50000,
      firstName: "Jules",
      lastname: "Johnsn",
      age: 26,
      gender: "Male",
      country: "United States",
      zipCode: 4321,
      occupation: "Employee",
      hobbies: "Speeding",
      startDate: "startDatePlus1M1D",
      insuranceSum: "7.000.000,00",
      meritRating: "Bonus 5",
      damageInsurance: "Partial Coverage",
      optionalEuroProtection: true,
      optionalLegalDefenseInsurance: true,
      courtesyCar: "No",
      priceSilver: "333.00",
      priceGold: "981.00",
      pricePlatinum: "1,927.00",
      priceUltimate: "3,670.00",
      email: "2410781005@fhb.at",
      username: "testCase13",
      password: "Password01",
      passwordConfirm: "Password01"
    },
    {
      name: "TC14 – Optional Products_3",
      make: "Ford",
      enginePerformance: 500,
      dateOfManufactor: "dateMinus3years",
      numerOfSeats: 5,
      fuelType: "Petrol",
      listPrice: 20000,
      annualMileage: 50000,
      firstName: "Steve",
      lastname: "MacIntosh",
      age: 26,
      gender: "Male",
      country: "United States",
      zipCode: 4321,
      occupation: "Employee",
      hobbies: "Speeding",
      startDate: "startDatePlus1M1D",
      insuranceSum: "7.000.000,00",
      meritRating: "Bonus 5",
      damageInsurance: "Partial Coverage",
      optionalEuroProtection: true,
      optionalLegalDefenseInsurance: false,
      courtesyCar: "No",
      priceSilver: "283.00",
      priceGold: "833.00",
      pricePlatinum: "1,636.00",
      priceUltimate: "3,117.00",
      email: "2410781005@fhb.at",
      username: "testCase14",
      password: "Password01",
      passwordConfirm: "Password01"
    },
    {
      name: "TC15 – Courtesy Car",
      make: "Ford",
      enginePerformance: 500,
      dateOfManufactor: "dateMinus3years",
      numerOfSeats: 5,
      fuelType: "Petrol",
      listPrice: 20000,
      annualMileage: 50000,
      firstName: "Mark",
      lastname: "Testberg",
      age: 26,
      gender: "Male",
      country: "United States",
      zipCode: 4321,
      occupation: "Employee",
      hobbies: "Speeding",
      startDate: "startDatePlus1M1D",
      insuranceSum: "7.000.000,00",
      meritRating: "Bonus 5",
      damageInsurance: "Partial Coverage",
      optionalEuroProtection: false,
      optionalLegalDefenseInsurance: true,
      courtesyCar: "Yes",
      priceSilver: "342.00",
      priceGold: "1,009.00",
      pricePlatinum: "1,980.00",
      priceUltimate: "3,772.00",
      email: "2410781005@fhb.at",
      username: "testCase15",
      password: "Password01",
      passwordConfirm: "Password01"
    },
    {
      name: "TC16 – Muss Failen",
      make: "Ford",
      enginePerformance: 500,
      dateOfManufactor: "dateMinus3years",
      numerOfSeats: 5,
      fuelType: "Petrol",
      listPrice: 20000,
      annualMileage: 50000,
      firstName: "Mark",
      lastname: "Testberg",
      age: 26,
      gender: "Male",
      country: "United States",
      zipCode: 4321,
      occupation: "Employee",
      hobbies: "Speeding",
      startDate: "startDatePlus1M1D",
      insuranceSum: "7.000.000,00",
      meritRating: "Super Bonus",
      damageInsurance: "Partial Coverage",
      optionalEuroProtection: false,
      optionalLegalDefenseInsurance: false,
      courtesyCar: "No",
      priceSilver: "342.00",
      priceGold: "1,009.00",
      pricePlatinum: "1,980.00",
      priceUltimate: "3,841.00",
      email: "2410781005@fhb.at",
      username: "testCase16",
      password: "Password01",
      passwordConfirm: "Password01"
    },
  ];
