version: 2.1

jobs:
  runner-test:
    machine: true
    resource_class: devopsgruppe3/testautomation
    steps:
      - checkout

      - run:
          name: Node.js & Abhängigkeiten installieren
          command: |
            curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt-get install -y nodejs
            node -v
            npm -v
            npm ci  # oder npm install, wenn kein package-lock.json vorhanden

      - run:
          name: TestCafe Tests ausführen
          command: |
            npx testcafe chrome tests/  # Passe ggf. den Pfad an

workflows:
  run-tests-lokal:
    jobs:
      - runner-test
