version: 2.1

jobs:
  runner-test:
    machine: true
    resource_class: devopsgruppe3/testautomation
    steps:
      - checkout

      - run:
          name: Node.js install pruefen
          command: |
            node -v
            npm -v

      - run:
          name: TestCafe Tests ausführen
          command: |
            npx testcafe chrome tests/ -r xunit:report/test-results/testcafe/results.xml 

      - store_test_results:
          path: report/test-results/testcafe/
      - store_artifacts:
          path: report/test-results/testcafe/

workflows:
  run-tests-lokal:
    jobs:
      - runner-test
