version: 2.1

jobs:
  runner-test:
    machine: true
    resource_class: devopsgruppe3/testautomation
    steps:
      - checkout

      - run:
          name: Node.js install pruefen
          command: |
            node -v
            npm -v

      - run:
          name: TestCafe Tests ausführen
          command: |
            npx testcafe chrome tests/

workflows:
  run-tests-lokal:
    jobs:
      - runner-test
